config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :followings, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :twitter_user
  validates :user_id, presence: false
  validates :content, presence: true, length: { maximum: 1000 }
  validates :age, presence: true
  validates :seibetsu, presence: true
  validates :genre, presence: true
  validates :past_time, presence: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/twitter_user.rb
class TwitterUser < ActiveRecord::Base
    
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    nickname = auth[:info][:nickname]
    image_url = auth[:info][:image]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end
  
  has_many :microposts
   
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :area , length: { maximum: 30 } ,allow_blank: true
  
  has_secure_password
  has_many :microposts
  
  #フォローしてる人
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  #フォローされてる人
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower 
  
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end

  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  helper_method :current_user, :logged_in?

  private
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  def current_user
    return unless session[:user_id]
    @current_user ||= TwitterUser.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
 #before_action :logged_in_user, only: [:create]

  def create
 
    @micropost = Micropost.new(micropost_params)
    
    if @micropost.save
      #render 'static_pages/done'
      flash[:success] = "お疲れ様でした！!あなたの次のチャンスへの扉が今開きました！!"
      redirect_to root_url
    else
      #@feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
      @micropost_all = Micropost.all.order(created_at: :desc)
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  def new
   @micropost = Micropost.new
   @user = current_user
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content,:seibetsu,:age,:past_time,:genre)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
before_action :logged_in_user

#ここから下にストロングパラーメーター追記
#  private

#  def relationships_params
#    params.require(:relationships).permit(:followed_id,:follower_id)
#  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = TwitterUser.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = Micropost.new
    @micropost_all = Micropost.all.order(created_at: :desc)
    @user  = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update,:home]
  before_action :correct_user, only: [:edit, :update]
  
  def show 
  #@user = User.find(params[:id])
  #@microposts = @user.microposts.order(created_at: :desc)
  #              .paginate(page: params[:page], per_page: 10)
  end
  
  def followings
    #@title = "Followings"
    #@user  = User.find(params[:id])
    #@users = @user.following_users
    #render 'show_follow'
  end

  def followers
    #@title = "Followers"
    #@user  = User.find(params[:id])
    #@users = @user.follower_users
    #render 'show_follow'
  end 
  
  def new
    #@user = User.new
  end
  
  def create
    #@user = User.new(user_params)
    #if @user.save
      #flash[:success] = "Welcome to the Sample App!"
      #redirect_to @user 
    #else
      #render 'new'
    #end
  end

  def edit
  
  end
  
  def home
  end
  
  def update
    #if @user.update(user_params)
      # 保存に成功した場合はトップページへリダイレクト
      #redirect_to @user, notice: 'メッセージを編集しました'
      #else
      # 保存に失敗した場合は編集画面へ戻す
      #render 'edit'
    #end
  end
  
  
  

  private

  def user_params
    #params.require(:user).permit(:name, :email, :bio, :area, :password,
    #                             :password_confirmation)
  end
  
  def set_user
    @user = TwitterUser.find(params[:id])
  end
  
  def correct_user
    #@user = User.find(params[:id])
    #redirect_to(root_url) unless @user == current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= TwitterUser.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="header">
  <div class="container">
    <!--<%= link_to "A★Kirameter", root_path, id: "logo" %>-->
    <nav>
      <ul class="nav navbar-nav navbar-right navber-text">
      <!---
      <% if logged_in? %>
      <li class="dropdown">
        <span class="dropdown-toggle" data-toggle="dropdown">
          <%= @user.nickname %>
          <b class="caret"></b>
          <%= image_tag(@user.image_url, :size => "32x32", :alt => "image", :class => "twitter_user_image") %>
        </span>
            <ul class="dropdown-menu">
              <!--<li><%= link_to "Profile", "" %></li>
              <li><%= link_to "Settings", "" %></li>
              <li class="divider"></li>--->
              <li><%= link_to 'logout', logout_path %></li>
            </ul>
      </li>
      <% else %>
      <%= link_to 'Twitter', 'auth/twitter' %>
      <% end %>
      --->
      



      </ul>
    </nav>
  </div>
</header>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/microposts/new.html.erb
<h2>アキラメ投稿画面</h2>
<div class="row">
 <div class="col-md-8 col-md-offset-2">
  <div class="">
  <%= render 'shared/akirame_tweet_form' %>
  </div>
 </div>
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_akirame_tweet_form.html.erb
<%= form_for(@micropost) do |f| %>
  <BR>
  <div>
   <%= render 'shared/error_messages', object: f.object %>
  </div>
  <div class="">
    <br>
    <%= f.text_area :content,class: 'akirame-tweet-form' ,placeholder: "アキラメたいこと、アキラメたことをここに書いてください" %>
      <div style="display:inline-flex" class="tweet_info">
   
        <%= f.radio_button :seibetsu,"男",class:'tweet-label',id:"inlineRadio1" %>　
        <label class="radio-inline tweet-label male-label" for="inlineRadio1">男</label>

        <%= f.radio_button :seibetsu,"女",class:'tweet-label',id:"inlineRadio2" %>
        <label class="radio-inline tweet-label female-label" for="inlineRadio2">女</label>

        <%= f.radio_button :seibetsu,"その他",class:'tweet-label',id:"inlineRadio3" %>
        <label class="radio-inline tweet-label malefemale-label" for="inlineRadio3">その他</label>
      </div>
      
      <div style="display:inline-flex" class="tweet-info">
        <% options = ["","10代","20代","30代","40代","50代","60代","70代","80代","90代","100歳以上"] %>
        <span class="tweet-label">年代</span>
        <%= f.select :age, options ,class: 'tweet-info' %>
        <% options = ["夢","目標","恋愛","人","仕事","生活","ちょっとしたこと","その他"] %>
        <span class="tweet-label">ジャンル</span>
        <%= f.select :genre, options ,class: 'tweet-info' %>
        <% options = ["","一瞬","1日","3日","１週間","1ヶ月","3ヶ月","6ヶ月","1年","2年","3年","4年","5年","6年","7年","8年","9年","10年","10年以上","15年以上","20年以上"] %>
        <span class="tweet-label">費やした時間</span>
        <%= f.select :past_time, options ,class: 'tweet-info' %>
      </div>
  </div>
<!-- <%= f.submit "アキラメる！", class: "akirame_btn",id: "akirame_btn" %> -->
<% end %>

 

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <!--<div class="alert alert-danger">-->
    <ul><span id="error_explanation">下記を確認シテください.</span>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_model.html.erb
<div id="modal-content">
	<p>「閉じる」か「背景」をクリックするとモーダルウィンドウを終了します。</p>
	<p><a id="modal-close" class="button-link">閉じる</a></p>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <BR>
  <div class="col-md-8 col-md-offset-2">
    <div class="center">
      <h1 id="logo-home" class="">A★Kirameter</h1>
      <hr>
      <h3>〜アキラメをキラメキ★に〜</h3>
      <p class="explain"> 今諦めたこと、今までに諦めたこと、これから諦めること</p>
      <BR>
        
      <div class="akirame-counter">
        <span class="data-label">Akirame.ALL</span>
        <br>
        <span id="akirameter">
        <%= pluralize(Micropost.count, "") %>
        </span>
      </div>

      <div class="col-md-4"><%= pie_chart Micropost.group(:age).count ,height: "200px",library: {backgroundColor: 'transparent',pieSliceText: 'label',legend: 'none',height: '180'} %></div>
      <div class="col-md-4"><%= pie_chart Micropost.group(:genre).count ,height: "200px",library: {backgroundColor: 'transparent',pieSliceText: 'label',legend: 'none',height: '180'}%></div>
      <div class="col-md-4"><%= pie_chart Micropost.group(:seibetsu).count ,height: "200px",library: {backgroundColor: 'transparent',pieSliceText: 'label',legend: 'none',colors:['#B0BEC5','#F48FB1','#b71c1c','#0D47A1'],height: '180'}%></div>
     
      <div class="col-md-8 col-md-offset-2 akirame-form">
          <%= render 'shared/akirame_tweet_form' %>
        <p><a id="modal-open" class="akirame_btn">アキラメる！</a></p>
      </div>
      
      <div style="display:inline-flex" class="share-btn">
        <%= render_shareable :buttons=> ['twitter'] %>
        <%= render_shareable :buttons=> ['facebook'] %>
      </div>
      
      <div class="akirame-tweets">
        <% @micropost_all.each do |m| %>
        <div class="field_contents">
          <div class="akirame">
            <%= m.content %>
          </div>
          <div class="akirame_info">
            <% if m.age.present? %><span class="age_info"><%= m.age %></span><% end %>
            <% if m.seibetsu.present? %><span class="seibetsu_info"><%= m.seibetsu %></span><% end %>
            <% if m.genre.present? %><span class="genre_info"><%= m.genre %></span><% end %>
            <% if m.past_time.present? %><span class="past_time_info"><%= m.past_time %></span><% end %>
            <br>
            <span class="created_info"><%= m.created_at %></span>
          </div>
        </div>
        <% end %>
      </div>
  　   <BR>
  　  <!---
     <%= link_to "Sign up now!", microposts_path, class: "btn btn-xs btn-primary" %>
     --->
    </div>
  </div>
  
  <!--モーダル画面1内-->
  <div id="modal-content1" class="col-md-6 col-md-offset-2">
	  <p class="">本当に諦めてもいいですか？</p>
	  <p class="non-deco"><a id="modal-close">ちょっと考えます</a></p>
	  <input type="button" value="はい、諦めます！" id="modal-submit" class="akirame_btn2">
  </div>
  
  <!--モーダル画面2内-->

  <div id="modal-content2" class="col-md-6 col-md-offset-2 animsition">
	  <p>お疲れ様でした！<br>また次のキラメキ探しましょう！</p>
  
  </div>
  <canvas id="canvas">
  </canvas>
</div>
2016---akirameter---

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-4">
    <div class="follow"><%= link_to gravatar_for(user, size: 100), user %></div><BR>
    <div class="follow"><%= user.name %></div><BR>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-2">
    <h2>edit_profile</h2>
    <h1><%= gravatar_for @user %></h1>
    <%= form_for @user,html: {class: "form-horizontal"} do |f| %>
      <% if @user.errors.present? %>
        <div class="alert alert-danger">
          <%= alert %>
        </div>
      <% end %>
    <label class="control-label" for="user_name">Name</label>
    <%= f.text_field :name,:class=>"form-control" %>
    <label class="control-label" for="user_email">E-mail</label>
    <%= f.text_field :email,:class=>"form-control" %>
    <label class="control-label" for="user_bio">Bio</label>
    <%= f.text_area :bio,:class=>"form-control", :rows=>"5" %>
    <label class="control-label" for="user_area">Area</label>
    <%= f.text_field :area,:class=>"form-control" %>
    <%= f.submit class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
        <%= @user.bio %><BR>
        <%= @user.area %>
       <%= render 'shared/stats' %>
    </section>
  </aside>
  
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <%= will_paginate @microposts %>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.erb
<!---provide? --->
<% provide(:title, @title) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
      <%= render 'shared/stats' %>
    </section>
    <section class="stats">
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <div class="users follow row">
        <%= render @users %>
      </div>
    <% end %>
  </div>
</div>